apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    operator: mesaque
    environment: prod
  name: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  loadBalancerIP: 35.237.90.72
  selector:
    app: wordpress